#!/usr/bin/env bash
# nixnet — environment capture
#
# Captures the machine's current state into the world repo so it survives
# machine destruction. Two things are captured:
#   1. Dotfiles (bashrc, profile, gitconfig, etc.) → hosts/<name>/files/
#   2. Explicitly installed packages → hosts/<name>/packages.yaml
#
# Captured state is restored by `nixnet apply` on a new machine.

# Files to capture — these are the bash environment and key config files
CAPTURE_FILES=(
    "$HOME/.bashrc"
    "$HOME/.bash_aliases"
    "$HOME/.bash_profile"
    "$HOME/.profile"
    "$HOME/.gitconfig"
    "$HOME/.inputrc"
    "$HOME/.ssh/config"
    "$HOME/.tmux.conf"
    "$HOME/.vimrc"
)

cmd_capture() {
    is_enrolled || die "Not enrolled. Run: nixnet enroll"

    local name
    name="$(current_identity)"

    capture_environment "$name"

    log_ok "Capture complete for ${name}"
    log_info "Run 'nixnet sync' to push captured state to remote"
}

# Main capture function — called by both enrollment and `nixnet capture`
capture_environment() {
    local name="$1"
    local host_dir="${NIXNET_WORLD}/hosts/${name}"
    local host_files_dir="${host_dir}/files"

    mkdir -p "$host_files_dir"

    capture_dotfiles "$name"
    capture_packages "$name"
}

# Copy dotfiles into world repo and generate files.yaml
capture_dotfiles() {
    local name="$1"
    local host_dir="${NIXNET_WORLD}/hosts/${name}"
    local host_files_dir="${host_dir}/files"
    local files_yaml="${host_dir}/files.yaml"
    local captured=0

    # Build list of files that actually exist
    local existing_files=()
    for f in "${CAPTURE_FILES[@]}"; do
        if [[ -f "$f" ]]; then
            existing_files+=("$f")
        fi
    done

    [[ ${#existing_files[@]} -gt 0 ]] || { log_info "No dotfiles found to capture"; return 0; }

    # Copy each file into the world repo
    for f in "${existing_files[@]}"; do
        local basename
        basename="$(basename "$f")"

        # Handle .ssh/config → ssh_config (flatten path)
        local dest_name="$basename"
        if [[ "$f" == *"/.ssh/config" ]]; then
            dest_name="ssh_config"
        fi

        cp "$f" "${host_files_dir}/${dest_name}"
        captured=$((captured + 1))
    done

    # Generate files.yaml with copy entries for each captured file
    cat > "$files_yaml" <<'HEADER'
# nixnet — captured environment files
# Auto-generated by nixnet capture. Edit freely — capture will regenerate.
files:
HEADER

    for f in "${existing_files[@]}"; do
        local basename
        basename="$(basename "$f")"
        local dest_name="$basename"
        local dest_path

        if [[ "$f" == *"/.ssh/config" ]]; then
            dest_name="ssh_config"
            dest_path="~/.ssh/config"
        else
            dest_path="~/${basename}"
        fi

        cat >> "$files_yaml" <<EOF
  - src: ${dest_name}
    dest: ${dest_path}
    method: copy
EOF
    done

    log_ok "Captured ${captured} dotfiles"
}

# Capture explicitly installed packages into packages.yaml
capture_packages() {
    local name="$1"
    local host_dir="${NIXNET_WORLD}/hosts/${name}"
    local pkg_yaml="${host_dir}/packages.yaml"

    # Get explicitly installed packages (not auto-installed dependencies)
    local pkg_list
    pkg_list="$(apt-mark showmanual 2>/dev/null | sort)"

    if [[ -z "$pkg_list" ]]; then
        log_warn "Could not read package list"
        return 0
    fi

    local pkg_count
    pkg_count="$(echo "$pkg_list" | wc -l)"

    # Write packages.yaml
    {
        echo "# nixnet — captured packages for ${name}"
        echo "# Auto-generated by nixnet capture. ${pkg_count} explicitly installed packages."
        echo "packages:"
        echo "$pkg_list" | while IFS= read -r pkg; do
            echo "  - ${pkg}"
        done
    } > "$pkg_yaml"

    log_ok "Captured ${pkg_count} packages"
}
